zarusz/SlimMessageBus

src/SlimMessageBus.Host.Unity/MessageBusBuilderExtensions.cs
src/SlimMessageBus.Host.Unity/Properties/AssemblyInfo.cs
src/SlimMessageBus.Host.Unity/SlimMessageBus.Host.Unity.csproj
src/SlimMessageBus.Host.Unity/SlimMessageBus.Host.Unity.nuspec
src/SlimMessageBus.Host.Unity/UnityMessageBusDependencyResolver.cs
src/SlimMessageBus.Host.Unity/packages.config
src/SlimMessageBus.sln

Unity plugin

---

src/SlimMessageBus.Host.Serialization.Avro/SlimMessageBus.Host.Serialization.Avro.csproj

Added the Sign off, let me know if the target branch is correct and if everything is Ok. Also, I signed it with the company email, if you need the personal email I can change it. 
Signed-off-by: Alberto Rojas <alberto.rojas@n5now.com>
Thanks again Tomasz

Add Contributors

---

docs/intro.md
docs/provider_azure_servicebus.md
docs/provider_kafka.md
src/SlimMessageBus.Host.AzureServiceBus/Consumer/ServiceBusConsumerContextExtensions.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusIt.cs

Document usage of IConsumerContextAware and ConsumerContext for transport extensions #27

---

README.md
docs/intro.md
src/Host.DI.Properties.xml
src/Samples/Sample.DomainEvents.WebApi/Properties/launchSettings.json
src/Samples/Sample.DomainEvents.WebApi/Startup.cs
src/Samples/Sample.Simple.ConsoleApp/Program.cs
src/SlimMessageBus.Host.AspNetCore/AspNetCoreMessageBusDependencyResolver.cs
src/SlimMessageBus.Host.AspNetCore/ServiceCollectionExtensions.cs
src/SlimMessageBus.Host.AspNetCore/SlimMessageBus.Host.AspNetCore.csproj
src/SlimMessageBus.Host.Autofac/AutofacMessageBusChildDependencyResolver.cs
src/SlimMessageBus.Host.Autofac/AutofacMessageBusDependencyResolver.cs
src/SlimMessageBus.Host.DependencyResolver/IChildDependencyResolver.cs
src/SlimMessageBus.Host.DependencyResolver/IDependencyResolver.cs
src/SlimMessageBus.Host.DependencyResolver/LookupDependencyResolver.cs
src/SlimMessageBus.Host.DependencyResolver/MessageBusCurrentProviderBuilder.cs
src/SlimMessageBus.Host.DependencyResolver/SlimMessageBus.Host.DependencyResolver.csproj
src/SlimMessageBus.Host.Memory/MemoryMessageBus.cs
src/SlimMessageBus.Host.MsDependencyInjection/MsDependencyInjectionChildDependencyResolver.cs
src/SlimMessageBus.Host.MsDependencyInjection/MsDependencyInjectionDependencyResolver.cs
src/SlimMessageBus.Host.MsDependencyInjection/ServiceCollectionExtensions.cs
src/SlimMessageBus.Host.MsDependencyInjection/SlimMessageBus.Host.MsDependencyInjection.csproj
src/SlimMessageBus.Host.ServiceLocator/ServiceLocatorMessageBusDependencyResolver.cs
src/SlimMessageBus.Host.Unity/UnityMessageBusChildDependencyResolver.cs
src/SlimMessageBus.Host.Unity/UnityMessageBusDependencyResolver.cs
src/SlimMessageBus.Host/Consumer/MessageProcessors/ConsumerInstanceMessageProcessor.cs
src/Tests/SlimMessageBus.Host.Memory.Test/MemoryMessageBusTest.cs
src/Tests/SlimMessageBus.Host.Test/Consumer/ConsumerInstanceMessageProcessorTest.cs
src/Tests/SlimMessageBus.Host.Test/Consumer/MessageBusMock.cs

Introduce an easier way to configure SMB when using MsDependencyResolution for DI:
```cs
// Startup.cs:
IServiceCollection services;
services.AddSlimMessageBus((mbb, svp) =>
{
mbb
.Produce<SomeMessage>(x => x.DefaultTopic("some-topic"))
// ...
.WithProviderKafka(new KafkaMessageBusSettings("localhost:9092"));
})
```

[Host.MsDependencyResolution] - Introduce a convenience SMB registration and configuration method 

---

README.md
docs/intro.md
src/Host.DI.Properties.xml
src/Samples/Sample.Simple.ConsoleApp/Program.cs
src/SlimMessageBus.Host.AspNetCore/ServiceCollectionExtensions.cs
src/SlimMessageBus.Host.MsDependencyInjection/IMessageBusConfigurator.cs
src/SlimMessageBus.Host.MsDependencyInjection/ServiceCollectionExtensions.cs

[Host.MsDependencyInjection] Using auto discovery on different assemblies #62

---

src/Host.Transport.Properties.xml
src/SlimMessageBus.Host.Hybrid/HybridMessageBus.cs
src/SlimMessageBus.Host.Memory/MemoryMessageBus.cs

[Host.Memory] Better error handling

---

src/SlimMessageBus.Host.AzureEventHub/EventHubMessageBus.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/SlimMessageBus.Host.Hybrid/HybridMessageBus.cs
src/SlimMessageBus.Host.Kafka/KafkaMessageBus.cs
src/SlimMessageBus.Host.Memory/MemoryMessageBus.cs
src/SlimMessageBus.Host/Collections/ProducerByMessageTypeCache.cs
src/SlimMessageBus.Host/Collections/SafeDictionaryWrapper.cs
src/SlimMessageBus.Host/MessageBusBase.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusTests.cs
src/Tests/SlimMessageBus.Host.Hybrid.Test/HybridMessageBusTest.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/KafkaMessageBusTest.cs
src/Tests/SlimMessageBus.Host.Memory.Test/MemoryMessageBusTest.cs
src/Tests/SlimMessageBus.Host.Test/Collections/ProducerByMessageTypeCacheTests.cs
src/Tests/SlimMessageBus.Host.Test/MessageBusBaseTest.cs
src/Tests/SlimMessageBus.Host.Test/SampleMessages.cs

- Introduce caching of message types and their base classes to faster handle polymorphic messages
- More consistent polymorphic handling across transports due to extraction of common routines
- More tests coverage

[Host.Transport] Improvements to polymorphic message handling

---

docs/provider_azure_eventhubs.md
src/SlimMessageBus.Host.AzureEventHub/EventHubMessageBus.cs
src/Tests/SlimMessageBus.Host.Test/MessageBusBaseTest.cs

[Host.AzureEventHub] Autocreate storage container if does not exist

---

src/SlimMessageBus.Host.AzureEventHub/SettingsExtensions.cs

[Host.AzureEventHub] Partition key provider should not be mandatory

---

src/Host.Transport.Properties.xml
src/SlimMessageBus.Host.Redis/Consumers/RedisListCheckerConsumer.cs
src/SlimMessageBus.Host.Redis/Consumers/RedisTopicConsumer.cs
src/SlimMessageBus.Host.Redis/RedisMessageBus.cs
src/SlimMessageBus.Host.Redis/SlimMessageBus.Host.Redis.csproj

[Host.Redis] Better logging and newest client

---

src/SlimMessageBus.Host.AzureServiceBus/SlimMessageBus.Host.AzureServiceBus.csproj
src/Tests/SlimMessageBus.Host.AzureEventHub.Test/SlimMessageBus.Host.AzureEventHub.Test.csproj
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/SlimMessageBus.Host.AzureServiceBus.Test.csproj
src/Tests/SlimMessageBus.Host.Hybrid.Test/SlimMessageBus.Host.Hybrid.Test.csproj
src/Tests/SlimMessageBus.Host.Kafka.Test/SlimMessageBus.Host.Kafka.Test.csproj
src/Tests/SlimMessageBus.Host.Memory.Test/SlimMessageBus.Host.Memory.Test.csproj
src/Tests/SlimMessageBus.Host.Redis.Test/SlimMessageBus.Host.Redis.Test.csproj
src/Tests/SlimMessageBus.Host.Test.Common/SlimMessageBus.Host.Test.Common.csproj
src/Tests/SlimMessageBus.Host.Test/SlimMessageBus.Host.Test.csproj
src/Tests/SlimMessageBus.Test/SlimMessageBus.Test.csproj

[Host.AzureServiceBus] Upgrade ASB client library

---

docs/intro.md
src/Host.DI.Properties.xml
src/Samples/Sample.DomainEvents.WebApi/Startup.cs
src/SlimMessageBus.Host.DependencyResolver/MessageBusCurrentProviderBuilder.cs
src/SlimMessageBus.Host.MsDependencyInjection/MessageBusCurrentProviderBuilderExtensions.cs

Improve docs and static accessor builder

---

docs/provider_redis.md
src/SlimMessageBus.Host.Redis/RedisMessageBus.cs
src/Tests/SlimMessageBus.Host.Redis.Test/RedisMessageBusIt.cs

Stabilize Redis integration tests

---

src/Host.Transport.Properties.xml
src/SlimMessageBus.Host.AzureEventHub/EventHubMessageBus.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/SlimMessageBus.Host.Hybrid/HybridMessageBus.cs
src/SlimMessageBus.Host.Kafka/KafkaMessageBus.cs
src/SlimMessageBus.Host.Memory/MemoryMessageBus.cs
src/SlimMessageBus.Host.Redis/RedisMessageBus.cs
src/SlimMessageBus.Host/IMessageBusProducer.cs
src/SlimMessageBus.Host/MessageBusBase.cs
src/SlimMessageBus.Host/MessageBusProxy.cs
src/Tests/SlimMessageBus.Host.Hybrid.Test/HybridMessageBusTest.cs
src/Tests/SlimMessageBus.Host.Test/MessageBusBaseTests.cs
src/Tests/SlimMessageBus.Host.Test/MessageBusTested.cs
src/Tests/SlimMessageBus.Host.Test/SampleMessages.cs

Fix for #99

---

src/Host.Transport.Properties.xml
src/SlimMessageBus.Host.AzureEventHub/SlimMessageBus.Host.AzureEventHub.csproj
src/SlimMessageBus.Host.AzureServiceBus/SlimMessageBus.Host.AzureServiceBus.csproj
src/SlimMessageBus.Host.Kafka/SlimMessageBus.Host.Kafka.csproj
src/SlimMessageBus.Host.Redis/SlimMessageBus.Host.Redis.csproj
src/SlimMessageBus.Host.Serialization.GoogleProtobuf/SlimMessageBus.Host.Serialization.GoogleProtobuf.csproj
src/Tests/SlimMessageBus.Host.Serialization.GoogleProtobuf.Test/SlimMessageBus.Host.Serialization.GoogleProtobuf.Test.csproj

Upgrade all transports libraries.

Upgrade transport libraries

---

docs/provider_azure_servicebus.md
src/Host.Transport.Properties.xml
src/Samples/Sample.Simple.ConsoleApp/Program.cs
src/SlimMessageBus.Host.AzureServiceBus/Config/ConsumerBuilderExtensions.cs
src/SlimMessageBus.Host.AzureServiceBus/Config/HasProviderExtensionsExtensions.cs
src/SlimMessageBus.Host.AzureServiceBus/Config/ProducerBuilderExtensions.cs
src/SlimMessageBus.Host.AzureServiceBus/MessageBusBuilderExtensions.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBusSettings.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusTopologyProvisioningSettings.cs
src/SlimMessageBus.Host.AzureServiceBus/TopicSubscriptionParams.cs
src/SlimMessageBus.Host/MessageBusBase.cs

[Host.AzureServiceBus] Ability to auto generate topology (queue/topic/subscription) in Azure Service Bus

---

README.md
src/Samples/Sample.Hybrid.ConsoleApp/appsettings.json
src/Samples/Sample.Serialization.ConsoleApp/Program.cs
src/Samples/Sample.Serialization.ConsoleApp/appsettings.json
src/Samples/Sample.Simple.ConsoleApp/Program.cs
src/Samples/Sample.Simple.ConsoleApp/appsettings.json
src/SlimMessageBus.Host.AzureEventHub/BuilderExtensions.cs
src/SlimMessageBus.Host.AzureEventHub/EventHubMessageBus.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/Tests/SlimMessageBus.Host.AzureEventHub.Test/appsettings.json
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/appsettings.json
src/Tests/SlimMessageBus.Host.Integration.Test/appsettings.json

Port samples and integration tests to the Azure subscription

Port to new Azure subscription

---

docs/provider_azure_servicebus.md
src/Host.Transport.Properties.xml
src/Samples/Sample.Simple.ConsoleApp/Program.cs
src/SlimMessageBus.Host.AzureServiceBus/Config/ConsumerBuilderExtensions.cs
src/SlimMessageBus.Host.AzureServiceBus/Config/SubscriptionSqlFilter.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusTopologyProvisioningSettings.cs

Introduces the feature requested in #114

[Host.AzureServiceBus] Supporting Subscription Sql Filter

---

docs/provider_azure_servicebus.md
src/Samples/Sample.Simple.ConsoleApp/Program.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBusSettings.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusTopologyService.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusTopologySettings.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusTests.cs

[Host.AzureMessageBus] Subscription was not created. #117

---

src/Samples/Sample.Simple.ConsoleApp/Program.cs
src/Samples/Sample.Simple.ConsoleApp/Sample.Simple.ConsoleApp.csproj

.NET Generic Host sample

---

docs/plugin_fluent_validation.md
src/Host.Interceptor.Properties.xml
src/Samples/Sample.ValidatingWebApi/Program.cs
src/SlimMessageBus.Host.FluentValidation.MsDependencyInjection/LambdaValidationErrorsInterceptor.cs
src/SlimMessageBus.Host.FluentValidation.MsDependencyInjection/ServiceCollectionExtensions.cs
src/SlimMessageBus.Host.FluentValidation/AbstractValidationInterceptor.cs
src/SlimMessageBus.Host.FluentValidation/ConsumerValidationInterceptor.cs
src/SlimMessageBus.Host.FluentValidation/HandlerValidationInterceptor.cs
src/SlimMessageBus.Host.FluentValidation/IValidationErrorsHandler.cs
src/SlimMessageBus.Host.FluentValidation/ProducerValidationInterceptor.cs
src/Tests/SlimMessageBus.Host.FluentValidation.Test/ConsumerValidationInterceptorTests.cs
src/Tests/SlimMessageBus.Host.FluentValidation.Test/HandlerValidationInterceptorTests.cs
src/Tests/SlimMessageBus.Host.FluentValidation.Test/ProducerValidationInterceptorTests.cs

```cc
builder.Services.AddValidationErrorsHandler(errors => new ApplicationException("Custom exception"));
```

FluentValidation - allow to specify user's own exception

---

src/Tests/SlimMessageBus.Host.AzureEventHub.Test/SlimMessageBus.Host.AzureEventHub.Test.csproj
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/SlimMessageBus.Host.AzureServiceBus.Test.csproj
src/Tests/SlimMessageBus.Host.Benchmark/SlimMessageBus.Host.Benchmark.csproj
src/Tests/SlimMessageBus.Host.FluentValidation.Test/SlimMessageBus.Host.FluentValidation.Test.csproj
src/Tests/SlimMessageBus.Host.Hybrid.Test/SlimMessageBus.Host.Hybrid.Test.csproj
src/Tests/SlimMessageBus.Host.Integration.Test/SlimMessageBus.Host.Integration.Test.csproj
src/Tests/SlimMessageBus.Host.Kafka.Test/SlimMessageBus.Host.Kafka.Test.csproj
src/Tests/SlimMessageBus.Host.Memory.Benchmark/AbstractMemoryBenchmark.cs
src/Tests/SlimMessageBus.Host.Memory.Benchmark/Properties/launchSettings.json
src/Tests/SlimMessageBus.Host.Memory.Benchmark/PubSubBenchmark.cs
src/Tests/SlimMessageBus.Host.Memory.Benchmark/ReqRespBenchmark.cs
src/Tests/SlimMessageBus.Host.Memory.Benchmark/SlimMessageBus.Host.Memory.Benchmark.csproj
src/Tests/SlimMessageBus.Host.Memory.Test/SlimMessageBus.Host.Memory.Test.csproj
src/Tests/SlimMessageBus.Host.Redis.Test/SlimMessageBus.Host.Redis.Test.csproj
src/Tests/SlimMessageBus.Host.Serialization.Benchmark/SlimMessageBus.Host.Serialization.Benchmark.csproj
src/Tests/SlimMessageBus.Host.Serialization.GoogleProtobuf.Test/SlimMessageBus.Host.Serialization.GoogleProtobuf.Test.csproj
src/Tests/SlimMessageBus.Host.Test/SlimMessageBus.Host.Test.csproj
src/Tests/SlimMessageBus.Test/SlimMessageBus.Test.csproj

Extend the existing benchmark tests with interceptor tests to understand overhead of interceptor pipeline.

[Core] Extend the benchmark tests with interceptor tests

---

src/Samples/Sample.ValidatingWebApi/Sample.ValidatingWebApi.csproj
src/SlimMessageBus.Host.AzureEventHub/SlimMessageBus.Host.AzureEventHub.csproj
src/SlimMessageBus.Host.AzureServiceBus/SlimMessageBus.Host.AzureServiceBus.csproj
src/SlimMessageBus.Host.FluentValidation/SlimMessageBus.Host.FluentValidation.csproj
src/SlimMessageBus.Host.Kafka/SlimMessageBus.Host.Kafka.csproj
src/SlimMessageBus.Host.Redis/RedisMessageBus.cs
src/SlimMessageBus.Host.Redis/SlimMessageBus.Host.Redis.csproj
src/SlimMessageBus.Host.Serialization.GoogleProtobuf/SlimMessageBus.Host.Serialization.GoogleProtobuf.csproj
src/Tests/SlimMessageBus.Host.AzureEventHub.Test/SlimMessageBus.Host.AzureEventHub.Test.csproj
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/SlimMessageBus.Host.AzureServiceBus.Test.csproj
src/Tests/SlimMessageBus.Host.FluentValidation.Test/SlimMessageBus.Host.FluentValidation.Test.csproj
src/Tests/SlimMessageBus.Host.Hybrid.Test/SlimMessageBus.Host.Hybrid.Test.csproj
src/Tests/SlimMessageBus.Host.Integration.Test/SlimMessageBus.Host.Integration.Test.csproj
src/Tests/SlimMessageBus.Host.Kafka.Test/SlimMessageBus.Host.Kafka.Test.csproj
src/Tests/SlimMessageBus.Host.Memory.Test/SlimMessageBus.Host.Memory.Test.csproj
src/Tests/SlimMessageBus.Host.Redis.Test/SlimMessageBus.Host.Redis.Test.csproj
src/Tests/SlimMessageBus.Host.Serialization.GoogleProtobuf.Test/SlimMessageBus.Host.Serialization.GoogleProtobuf.Test.csproj
src/Tests/SlimMessageBus.Host.Test.Common/SlimMessageBus.Host.Test.Common.csproj
src/Tests/SlimMessageBus.Host.Test/SlimMessageBus.Host.Test.csproj
src/Tests/SlimMessageBus.Test/SlimMessageBus.Test.csproj

Upgrade client libraries to latest

Upgrade client libraries to latest

---

src/Host.Transport.Properties.xml
src/SlimMessageBus.Host.Redis/Consumers/RedisListCheckerConsumer.cs
src/SlimMessageBus.Host.Redis/Consumers/RedisTopicConsumer.cs

[Host.Redis] Error logged every time while processing redi pub/sub topic #140

---

docs/intro.md

Add information about how to achieve generic interceptors

---

docs/provider_hybrid.md
src/.editorconfig
src/Host.Transport.Properties.xml
src/SlimMessageBus.Host.Hybrid/HybridMessageBus.cs
src/SlimMessageBus.Host.Hybrid/HybridMessageBusSettings.cs
src/SlimMessageBus.Host.Hybrid/MessageBusBuilderExtensions.cs
src/SlimMessageBus.Host/Config/Fluent/MessageBusBuilder.cs
src/SlimMessageBus.Host/Config/MessageBusSettings.cs
src/SlimMessageBus.Host/MessageBusBase.cs
src/SlimMessageBus.sln
src/Tests/SlimMessageBus.Host.Hybrid.Test/HybridMessageBusTest.cs
src/Tests/SlimMessageBus.Host.Test/Config/MessageBusBuilderTests.cs

[Host.Hybrid] Support to publish event to more than one child bus if event type match

---

.github/workflows/build.yml
src/Common.Properties.xml
src/Host.DI.Properties.xml
src/Host.Interceptor.Properties.xml
src/Host.Serialization.Properties.xml
src/Host.Transport.Properties.xml
src/SlimMessageBus.Host.DependencyResolver/SlimMessageBus.Host.DependencyResolver.csproj
src/SlimMessageBus.Host.Interceptor/SlimMessageBus.Host.Interceptor.csproj
src/SlimMessageBus.Host.Serialization/SlimMessageBus.Host.Serialization.csproj
src/SlimMessageBus/SlimMessageBus.csproj

Prepare release

---

docs/NuGet.md
src/Common.Properties.xml
src/Host.Serialization.Properties.xml
src/Host.Transport.Properties.xml
src/Samples/Sample.DomainEvents.Application/OrderSubmittedHandler.cs
src/Samples/Sample.DomainEvents.Domain/GlobalSuppressions.cs
src/Samples/Sample.DomainEvents.Domain/OrderSubmittedEvent.cs
src/Samples/Sample.DomainEvents.WebApi/Controllers/OrdersController.cs
src/Samples/Sample.DomainEvents.WebApi/Controllers/ValuesController.cs
src/Samples/Sample.DomainEvents.WebApi/GlobalSuppressions.cs
src/Samples/Sample.DomainEvents.WebApi/Properties/launchSettings.json
src/Samples/Sample.DomainEvents.WebApi/Sample.DomainEvents.WebApi.csproj
src/Samples/Sample.DomainEvents.WebApi/Startup.cs
src/SlimMessageBus.Host.AspNetCore/SlimMessageBus.Host.AspNetCore.csproj
src/SlimMessageBus.Host.AsyncApi/SlimMessageBus.Host.AsyncApi.csproj
src/SlimMessageBus.Host.AzureEventHub/SlimMessageBus.Host.AzureEventHub.csproj
src/SlimMessageBus.Host.AzureServiceBus/SlimMessageBus.Host.AzureServiceBus.csproj
src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj
src/SlimMessageBus.Host.FluentValidation/SlimMessageBus.Host.FluentValidation.csproj
src/SlimMessageBus.Host.Interceptor/SlimMessageBus.Host.Interceptor.csproj
src/SlimMessageBus.Host.Kafka/SlimMessageBus.Host.Kafka.csproj
src/SlimMessageBus.Host.Memory/SlimMessageBus.Host.Memory.csproj
src/SlimMessageBus.Host.Outbox.DbContext/SlimMessageBus.Host.Outbox.DbContext.csproj
src/SlimMessageBus.Host.Outbox.Sql/SlimMessageBus.Host.Outbox.Sql.csproj
src/SlimMessageBus.Host.Redis/SlimMessageBus.Host.Redis.csproj
src/SlimMessageBus.Host.Serialization/SlimMessageBus.Host.Serialization.csproj
src/SlimMessageBus.Host/SlimMessageBus.Host.csproj
src/SlimMessageBus/SlimMessageBus.csproj

Introduce README.md on published NuGet packages (#89)

---

src/Host.Transport.Properties.xml
src/SlimMessageBus.Host.AsyncApi/MessageBusDocumentGenerator.cs

Append the subscription name or consumer group to the channel ID.

[Host.AsyncAPI] Allow multiple subscribers on one topic

---

docs/provider_redis.md

Clarify Redis docs #170

---

.github/workflows/build.yml
README.md
build/tasks.ps1
docs/provider_mqtt.md
src/Host.Transport.Properties.xml
src/SlimMessageBus.Host.AzureServiceBus/Config/HasProviderExtensionsExtensions.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/SlimMessageBus.Host.Mqtt/Config/HasProviderExtensionsExtensions.cs
src/SlimMessageBus.Host.Mqtt/Config/MessageBusBuilderExtensions.cs
src/SlimMessageBus.Host.Mqtt/Config/ProducerBuilderExtensions.cs
src/SlimMessageBus.Host.Mqtt/GlobalUsings.cs
src/SlimMessageBus.Host.Mqtt/MqttMessageBus.cs
src/SlimMessageBus.Host.Mqtt/MqttMessageBusSettings.cs
src/SlimMessageBus.Host.Mqtt/MqttTopicConsumer.cs
src/SlimMessageBus.Host.Mqtt/SlimMessageBus.Host.Mqtt.csproj
src/SlimMessageBus.Host.Redis/Consumers/RedisListCheckerConsumer.cs
src/SlimMessageBus.Host.Redis/Consumers/RedisTopicConsumer.cs
src/SlimMessageBus.Host/Consumer/AbstractConsumer.cs
src/SlimMessageBus.Host/Consumer/MessageProcessors/ConsumerInstanceMessageProcessor.cs
src/SlimMessageBus.sln
src/Tests/SlimMessageBus.Host.Mqtt.Test/GlobalUsings.cs
src/Tests/SlimMessageBus.Host.Mqtt.Test/MqttMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Mqtt.Test/SlimMessageBus.Host.Mqtt.Test.csproj
src/Tests/SlimMessageBus.Host.Mqtt.Test/Usings.cs
src/Tests/SlimMessageBus.Host.Mqtt.Test/appsettings.json
src/Tests/SlimMessageBus.Host.Redis.Test/RedisMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Test.Common/IntegrationTest/BaseIntegrationTest.cs

[Host.Mqtt] The MQTT transport

---

src/Host.Transport.Properties.xml
src/SlimMessageBus.Host.AsyncApi/MessageBusDocumentGenerator.cs

[Host.AsyncApi] Remove references to non existing bindings

---

.github/workflows/build.yml

Allow to share secrets for forked PR builds

[Actions] Change PR trigger

---

.github/workflows/build.yml

[Actions] Segregate unit tests away from integration tests

---

.github/workflows/build.yml

Supress integration tests from forked PRs

---

README.md
src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.AsyncApi/MessageBusDocumentGenerator.cs
src/SlimMessageBus.Host.AzureEventHub/Config/SettingsExtensions.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusTopologyService.cs
src/SlimMessageBus.Host.Configuration/Builders/ConsumerBuilder.cs
src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj
src/SlimMessageBus.Host.Mqtt/MqttMessageBus.cs
src/SlimMessageBus.Host.Outbox.Sql/SqlHelper.cs
src/SlimMessageBus.Host.Outbox.Sql/SqlOutboxRepository.cs
src/SlimMessageBus.Host.Outbox/Configuration/MessageBusBuilderExtensions.cs
src/SlimMessageBus.Host/Collections/KindMapping.cs
src/SlimMessageBus.Host/Collections/RuntimeTypeCache.cs
src/SlimMessageBus.Host/Consumer/MessageScopeWrapper.cs
src/SlimMessageBus.Host/Helpers/ReflectionUtils.cs
src/SlimMessageBus.Host/Hybrid/HybridMessageBus.cs
src/SlimMessageBus.Host/MessageBusBase.cs
src/SlimMessageBus.Host/RequestResponse/InMemoryPendingRequestStore.cs
src/Tests/SlimMessageBus.Host.Mqtt.Test/MqttMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Test/Consumer/CheckpointTriggerTest.cs
src/Tests/SlimMessageBus.Host.Test/Consumer/MessageScopeWrapperTest.cs
src/Tools/SecretStore/SecretService.cs

- Overall refactor
- Improve metrics in SonarCloud

Refactor Following SonarCloud part 2

---

src/SlimMessageBus.Host.Kafka/Consumer/KafkaGroupConsumer.cs

Fix sonar reported bug

---

build/md-preprocessor.ps1
docs/plugin_asyncapi.t.md
docs/plugin_outbox.md
docs/plugin_outbox.t.md
src/Samples/Sample.AsyncApi.Service/Program.cs
src/Samples/Sample.OutboxWebApi/Application/CreateCustomerCommand.cs
src/Samples/Sample.OutboxWebApi/Application/CreateCustomerCommandHandler.cs
src/Samples/Sample.OutboxWebApi/GlobalUsings.cs
src/Samples/Sample.OutboxWebApi/Program.cs

* Adjust docs (some corrections)
* Introduce md fragment extraction script

Adjust docs

---

.github/workflows/build.yml

Allow to pass secrets for cloned repo PRs (part 2)

---

.github/workflows/build.yml

Sonar diff analysis for external PRs

---

src/Host.Plugin.Properties.xml
src/Samples/Sample.AsyncApi.Service/Sample.AsyncApi.Service.csproj
src/Samples/Sample.DomainEvents.WebApi/Sample.DomainEvents.WebApi.csproj
src/Samples/Sample.Images.Worker/Sample.Images.Worker.csproj
src/Samples/Sample.OutboxWebApi/Sample.OutboxWebApi.csproj
src/SlimMessageBus.Host.AzureEventHub/SlimMessageBus.Host.AzureEventHub.csproj
src/SlimMessageBus.Host.AzureServiceBus/SlimMessageBus.Host.AzureServiceBus.csproj
src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj
src/SlimMessageBus.Host.Redis/SlimMessageBus.Host.Redis.csproj
src/SlimMessageBus.Host.Serialization.GoogleProtobuf/SlimMessageBus.Host.Serialization.GoogleProtobuf.csproj
src/Tests/Host.Test.Properties.xml
src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/SlimMessageBus.Host.Outbox.DbContext.Test.csproj
src/Tests/SlimMessageBus.Host.Serialization.GoogleProtobuf.Test/SlimMessageBus.Host.Serialization.GoogleProtobuf.Test.csproj

Update client libraries

---

src/SlimMessageBus.Host.Serialization.Hybrid/SerializationBuilderExtensions.cs
src/Tests/SlimMessageBus.Host.Serialization.Hybrid.Test/SerializationBuilderExtensionsTests.cs

Resolve SonarCloud issues created by #239

Resolve SonarCloud warnings created by PR #239 / Issue #238

---

docs/serialization.md

Clean serialization.md docs

---

src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.Outbox.DbContext/Configuration/MessageBusBuilderExtensions.cs
src/SlimMessageBus.Host.Outbox.Sql/Configuration/MessageBusBuilderExtensions.cs
src/SlimMessageBus.Host/Helpers/ReflectionUtils.cs

[Host.Outbox] Cannot resolve IOutboxMigratonService from a singleton

---

src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.Serialization.SystemTextJson/JsonMessageSerializer.cs
src/SlimMessageBus.Host.Serialization.SystemTextJson/SerializationBuilderExtensions.cs
src/Tests/SlimMessageBus.Host.Serialization.SystemTextJson.Test/JsonMessageSerializerTests.cs
src/Tests/SlimMessageBus.Host.Serialization.SystemTextJson.Test/Usings.cs

[Host.Serialization.SystemTextJson] Error when using JsonMessageSerializer with default settings #252

---

src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusTopologyService.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusTopologySettings.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusIt.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusTopologyServiceTests.cs

[Host.AzureServiceBus] $Default rule is not added to subscription #254

---

src/.editorconfig
src/Host.Plugin.Properties.xml
src/Samples/Sample.AsyncApi.Service/Sample.AsyncApi.Service.csproj
src/Samples/Sample.DomainEvents.WebApi/Sample.DomainEvents.WebApi.csproj
src/Samples/Sample.Images.Worker/Sample.Images.Worker.csproj
src/Samples/Sample.OutboxWebApi/Sample.OutboxWebApi.csproj
src/Samples/Sample.ValidatingWebApi/Sample.ValidatingWebApi.csproj
src/SlimMessageBus.Host.AzureEventHub/SlimMessageBus.Host.AzureEventHub.csproj
src/SlimMessageBus.Host.AzureServiceBus/SlimMessageBus.Host.AzureServiceBus.csproj
src/SlimMessageBus.Host.FluentValidation/SlimMessageBus.Host.FluentValidation.csproj
src/SlimMessageBus.Host.Kafka/SlimMessageBus.Host.Kafka.csproj
src/SlimMessageBus.Host.Mqtt/SlimMessageBus.Host.Mqtt.csproj
src/SlimMessageBus.Host.Serialization.GoogleProtobuf/SlimMessageBus.Host.Serialization.GoogleProtobuf.csproj
src/SlimMessageBus.Host.Sql.Common/SlimMessageBus.Host.Sql.Common.csproj
src/Tests/Host.Test.Properties.xml
src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/SlimMessageBus.Host.Outbox.DbContext.Test.csproj
src/Tests/SlimMessageBus.Host.Serialization.GoogleProtobuf.Test/SlimMessageBus.Host.Serialization.GoogleProtobuf.Test.csproj
src/Tests/SlimMessageBus.Host.Test.Common/SlimMessageBus.Host.Test.Common.csproj

- Update transport client/drivers to latest
- Update other libs to latest

Update libraries to latest

---

src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.AzureEventHub/EventHubMessageBus.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/SlimMessageBus.Host.Kafka/KafkaMessageBus.cs
src/SlimMessageBus.Host.Memory/MemoryMessageBus.cs
src/SlimMessageBus.Host.Mqtt/MqttMessageBus.cs
src/SlimMessageBus.Host.Outbox/Interceptors/OutboxSendingTask.cs
src/SlimMessageBus.Host.RabbitMQ/RabbitMqMessageBus.cs
src/SlimMessageBus.Host.Redis/RedisMessageBus.cs
src/SlimMessageBus.Host.Sql/GlobalUsings.cs
src/SlimMessageBus.Host.Sql/SqlMessageBus.cs
src/SlimMessageBus.Host/IMessageBusBulkProducer.cs
src/SlimMessageBus.Host/MessageBusBase.cs
src/SlimMessageBus.Host/Retry.cs
src/Tests/SlimMessageBus.Host.Outbox.Test/Interceptors/OutboxSendingTaskTests.cs
src/Tests/SlimMessageBus.Host.Test/MessageBusTested.cs

Refactor to make things consistent following the last set of PRs.

Refactor iteration

---

docs/intro.md
docs/intro.t.md
src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj
src/SlimMessageBus.Host/Consumer/IMessageScopeAccessor.cs
src/SlimMessageBus.Host/Consumer/MessageScopeAccessor.cs
src/SlimMessageBus.Host/Consumer/MessageScopeWrapper.cs
src/SlimMessageBus.Host/DependencyResolver/ServiceCollectionExtensions.cs
src/Tests/SlimMessageBus.Host.Integration.Test/MessageBusCurrent/MessageBusCurrentTests.cs
src/Tests/SlimMessageBus.Host.Integration.Test/MessageScopeAccessor/MessageScopeAccessorTests.cs

[Host] Introduce IMessageScopeAccessor to wrap the MessageScope

---

docs/provider_memory.md
docs/provider_memory.t.md
src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.Memory/MemoryMessageBus.cs
src/SlimMessageBus.Host.Memory/MemoryMessageBusSettings.cs
src/Tests/SlimMessageBus.Host.Memory.Test/MemoryMessageBusTests.cs

[Host.Memory] Ability to use headers in Memory provider without enabling message serialization

---

src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.Outbox.Sql/SqlOutboxMigrationService.cs
src/SlimMessageBus.Host.Outbox.Sql/SqlOutboxRepository.cs
src/SlimMessageBus.Host.Outbox.Sql/SqlOutboxTemplate.cs

[Host.Outbox] Execute permission is required for Outbox #297

---

docs/intro.md
docs/intro.t.md
docs/provider_kafka.t.md
docs/provider_rabbitmq.md
src/SlimMessageBus.Host.AzureEventHub/Consumer/EhPartitionConsumerForConsumers.cs
src/SlimMessageBus.Host.AzureEventHub/Consumer/IEventHubConsumerErrorHandler.cs
src/SlimMessageBus.Host.AzureServiceBus/Consumer/IServiceBusConsumerErrorHandler.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/SlimMessageBus.Host.Kafka/Consumer/IKafkaConsumerErrorHandler.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaConsumerContextExtensions.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaPartitionConsumerForConsumers.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaPartitionConsumerForResponses.cs
src/SlimMessageBus.Host.Mqtt/IMqttConsumerErrorHandler.cs
src/SlimMessageBus.Host.Mqtt/MqttMessageBus.cs
src/SlimMessageBus.Host.Nats/INatsConsumerErrorHandler.cs
src/SlimMessageBus.Host.Nats/NatsMessageBus.cs
src/SlimMessageBus.Host.Redis/Consumers/IRedisConsumerErrorHandler.cs
src/SlimMessageBus.Host.Redis/RedisMessageBus.cs
src/SlimMessageBus.Host/Consumer/Checkpointing/CheckpointTriggerFactory.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/KafkaMessageBusIt.cs

Clarify Kafka docs. Add Kafka transport-specific error handler interface.
Related with #131

Clarify Kafka docs

---

src/SlimMessageBus.Host/Helpers/ReflectionUtils.cs

remove unused method `GenerateGetterExpr`
Signed-off-by: krivchenko_kv <kvkrivchenko@activebc.ru>

#302 Update ReflectionUtils.cs

---

.github/workflows/build.yml
src/Tests/SlimMessageBus.Host.Kafka.Test/appsettings.json

* Use the https://github.com/dorny/test-reporter plugin to visualize inside GitHub actions
* Output tests in `trx` format

[DevOps] Improve how test results are collected and presented

---

src/Samples/Sample.AsyncApi.Service/Controllers/WeatherForecastController.cs
src/Samples/Sample.Images.Worker/GlobalSuppressions.cs
src/Samples/Sample.Nats.WebApi/PingConsumer.cs
src/SlimMessageBus.Host.AzureEventHub/Config/BuilderExtensions.cs
src/SlimMessageBus.Host.AzureEventHub/Consumer/EhPartitionConsumerForResponses.cs
src/SlimMessageBus.Host.Configuration/Builders/MessageBusBuilder.cs
src/SlimMessageBus.Host.Configuration/Settings/HasProviderExtensions.cs
src/SlimMessageBus.Host.Mqtt/MqttTopicConsumer.cs
src/SlimMessageBus.Host.Outbox/Interceptors/OutboxForwardingPublishInterceptor.cs
src/SlimMessageBus.Host.Outbox/Services/OutboxSendingTask.cs
src/SlimMessageBus.Host.Sql.Common/CommonSqlMigrationService.cs
src/SlimMessageBus.Host/Collections/KindMapping.cs
src/SlimMessageBus.Host/Collections/SafeDictionaryWrapper.cs
src/SlimMessageBus.Host/Consumer/AbstractConsumer.cs
src/SlimMessageBus.Host/Consumer/MessageProcessors/MessageProcessor.cs
src/SlimMessageBus.Host/Consumer/MessageScopeWrapper.cs
src/SlimMessageBus.Host/DependencyResolver/ServiceCollectionExtensions.cs
src/SlimMessageBus.Host/GlobalSuppressions.cs
src/SlimMessageBus.Host/Hybrid/HybridMessageBus.cs
src/SlimMessageBus.Host/MessageBusBase.cs
src/SlimMessageBus.Host/MessageWithHeadersSerializer.cs
src/SlimMessageBus.Host/Producer/InterceptorPipelines/PublishInterceptorPipeline.cs
src/SlimMessageBus.Host/Producer/InterceptorPipelines/SendInterceptorPipeline.cs
src/SlimMessageBus.Host/RequestResponse/PendingRequestManager.cs
src/Tests/SlimMessageBus.Host.Memory.Test/Consumers/ConcurrentMessageProcessorQueueTests.cs
src/Tests/SlimMessageBus.Host.Memory.Test/Consumers/MessageProcessorQueueTests.cs
src/Tests/SlimMessageBus.Host.Test/Consumer/MessageScopeWrapperTest.cs
src/Tests/SlimMessageBus.Host.Test/Helpers/ReflectionUtilsTests.cs

Signed-off-by: krivchenko_kv <kvkrivchenko@activebc.ru>

Fix sonar warnings

---

src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.Configuration/Builders/MessageBusBuilder.cs
src/SlimMessageBus.Host.Configuration/Settings/MessageBusSettings.cs
src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj
src/SlimMessageBus.Host/DependencyResolver/ServiceCollectionExtensions.cs
src/SlimMessageBus.Host/MessageBusBase.cs

Tweaks after #307

---

src/.editorconfig
src/SlimMessageBus.Host.Kafka/Consumer/KafkaGroupConsumer.cs
src/SlimMessageBus.Host.Memory/MemoryMessageBus.cs
src/SlimMessageBus.Host.Nats/NatsSubjectConsumer.cs
src/SlimMessageBus.Host.Outbox/Services/OutboxSendingTask.cs
src/SlimMessageBus.Host/Consumer/AbstractConsumer.cs
src/SlimMessageBus.Host/MessageBusBase.cs
src/SlimMessageBus.Host/PlatformExtensions.cs
src/Tests/SlimMessageBus.Host.Outbox.Test/Services/OutboxSendingTaskTests.cs
src/Tests/SlimMessageBus.Host.Test/Helpers/ReflectionUtilsTests.cs

Sonar tweaks

---

src/SlimMessageBus.Host.Outbox.Sql/SqlOutboxMessageRepository.cs
src/SlimMessageBus.Host.Outbox/Interceptors/OutboxForwardingPublishInterceptor.cs
src/SlimMessageBus.Host.Outbox/Repositories/IHasId.cs
src/SlimMessageBus.Host.Outbox/Repositories/IOutboxMessageFactory.cs
src/SlimMessageBus.Host.Outbox/Repositories/OutboxMessage.cs
src/Tests/SlimMessageBus.Host.Outbox.Sql.Test/BaseSqlOutboxRepositoryTest.cs
src/Tests/SlimMessageBus.Host.Outbox.Sql.Test/SqlOutboxRepositoryTests.cs
src/Tests/SlimMessageBus.Host.Outbox.Test/Interceptors/OutboxForwardingPublishInterceptorTests.cs

Signed-off-by: krivchenko_kv <kvkrivchenko@activebc.ru>
[Host.Outbox]
HasId interfcace as a specification for the Create method

uuidv7: [Host.Outrbox] added HasId abstraction

---

.github/workflows/build.yml
docs/provider_kafka.md
docs/provider_kafka.t.md
src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.Configuration/Builders/AbstractConsumerBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/ConsumerBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/IBuilderWithSettings.cs
src/SlimMessageBus.Host.Configuration/Builders/IConsumerBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/IProducerBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/MessageBusBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/ProducerBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/RequestResponseBuilder.cs
src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj
src/SlimMessageBus.Host.Kafka/Configs/KafkaAbstractConsumerBuilderExtensions.cs
src/SlimMessageBus.Host.Kafka/Configs/KafkaDelegates.cs
src/SlimMessageBus.Host.Kafka/Configs/KafkaProducerBuilderExtensions.cs
src/SlimMessageBus.Host.Kafka/Configs/KafkaProducerSettingsExtensions.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaExtensions.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaPartitionConsumer.cs
src/SlimMessageBus.Host.Kafka/KafkaMessageBus.cs
src/SlimMessageBus.Host.Kafka/KafkaMessageBusSettingsValidationService.cs
src/SlimMessageBus.sln
src/Tests/SlimMessageBus.Host.Kafka.Test/Config/KafkaProducerBuilderExtensionsTest.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/KafkaMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/KafkaMessageBusTest.cs

[Host.Kafka] Support for High-Throughput Publishing to Kafka

---

src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj
src/SlimMessageBus.Host.Nats/SlimMessageBus.Host.Nats.csproj
src/Tests/Host.Test.Properties.xml
src/Tests/SlimMessageBus.Host.Outbox.Sql.Test/SlimMessageBus.Host.Outbox.Sql.Test.csproj

Prepare 2.6.0 release + lib updates

---

.github/workflows/build.yml
docs/provider_kafka.md
docs/provider_kafka.t.md
src/SlimMessageBus.Host.Configuration/Builders/AbstractConsumerBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/ConsumerBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/IBuilderWithSettings.cs
src/SlimMessageBus.Host.Configuration/Builders/IConsumerBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/IProducerBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/MessageBusBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/ProducerBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/RequestResponseBuilder.cs
src/SlimMessageBus.Host.Kafka/Configs/KafkaAbstractConsumerBuilderExtensions.cs
src/SlimMessageBus.Host.Kafka/Configs/KafkaDelegates.cs
src/SlimMessageBus.Host.Kafka/Configs/KafkaProducerBuilderExtensions.cs
src/SlimMessageBus.Host.Kafka/Configs/KafkaProducerSettingsExtensions.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaExtensions.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaPartitionConsumer.cs
src/SlimMessageBus.Host.Kafka/KafkaMessageBus.cs
src/SlimMessageBus.Host.Kafka/KafkaMessageBusSettingsValidationService.cs
src/SlimMessageBus.Host.Nats/SlimMessageBus.Host.Nats.csproj
src/SlimMessageBus.sln
src/Tests/Host.Test.Properties.xml
src/Tests/SlimMessageBus.Host.AzureEventHub.Test/EventHubMessageBusIt.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/Config/KafkaProducerBuilderExtensionsTest.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/KafkaMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/KafkaMessageBusTest.cs
src/Tests/SlimMessageBus.Host.Memory.Test/MemoryMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Mqtt.Test/MqttMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Nats.Test/NatsMessageBusIt.cs

Merge v2 to v3

---

src/Host.Plugin.Properties.xml
src/Tests/SlimMessageBus.Host.AmazonSQS.Test/SqsMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Test/MessageBusBaseTests.cs

AmazonSQS - improve flaky integration tests

---

docs/intro.md
docs/intro.t.md
src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.Configuration/Builders/MessageBusBuilder.cs
src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj
src/SlimMessageBus.Host/Consumer/Context/ConsumerContext.cs
src/SlimMessageBus.Host/Consumer/IMessageScope.cs
src/SlimMessageBus.Host/Consumer/MessageProcessors/IMessageProcessor.cs
src/SlimMessageBus.Host/Consumer/MessageProcessors/MessageHandler.cs
src/SlimMessageBus.Host/Consumer/MessageProcessors/MessageProcessor.cs
src/SlimMessageBus.Host/DependencyResolver/ServiceCollectionExtensions.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusTests.cs
src/Tests/SlimMessageBus.Host.Integration.Test/MessageScopeAccessor/MessageScopeAccessorTests.cs
src/Tests/SlimMessageBus.Host.Memory.Test/MemoryMessageBusTests.cs
src/Tests/SlimMessageBus.Host.Test/Consumer/ConsumerInstanceMessageProcessorTest.cs
src/Tests/SlimMessageBus.Host.Test/Consumer/MessageBusMock.cs
src/Tests/SlimMessageBus.Host.Test/MessageBusBaseTests.cs

- The interface `IConsumerContext` will be injectable now.
- Improved docs.
- Closes #388.

[Host] Expose IConsumerContext via MSDI

---

src/Samples/Sample.Simple.ConsoleApp/Program.cs

Based on conversations in #405 this wraps the sample's message sending loop in a DI scope

Improve sample to work inside ASP.NET context #405

---

src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.AmazonSQS/ClientFactory/AbstractTemporaryCredentialsSqsClientProvider.cs
src/SlimMessageBus.Host.AmazonSQS/Consumer/SqsBaseConsumer.cs
src/SlimMessageBus.Host.AmazonSQS/Services/SqsTopologyCache.cs
src/SlimMessageBus.Host.AmazonSQS/Services/SqsTopologyService.cs
src/SlimMessageBus.Host.AmazonSQS/SlimMessageBus.Host.AmazonSQS.csproj
src/Tests/SlimMessageBus.Host.AmazonSQS.Test/ClientFactory/SqsCacheServiceTest.cs
src/Tests/SlimMessageBus.Host.AmazonSQS.Test/SqsMessageBusIt.cs
src/Tests/SlimMessageBus.Host.AmazonSQS.Test/SqsTopologyServiceTest.cs

[Host.AmazonSQS] Upgrade AWS SQS to v4
