zarusz/SlimMessageBus

docs/provider_memory.md
src/Samples/Sample.DomainEvents.WebApi/Startup.cs

This pull request fixes the same code and documentation regarding the `InMemoryBus` and the auto-registration for producers and consumers.
The existing code failed to register the producers, leading to an unusable example for newcomers.
Closes #40

Fix sample and documentation code regarding auto registration

---

docs/intro.md
src/Host.Transport.Properties.xml
src/SlimMessageBus.Host/Config/Fluent/AbstractConsumerBuilder.cs
src/SlimMessageBus.Host/Config/Fluent/AbstractTopicConsumerBuilder.cs
src/SlimMessageBus.Host/Config/Fluent/TopicConsumerBuilder.cs
src/SlimMessageBus.Host/Config/Fluent/TopicHandlerBuilder.cs

Following the issue found on Gitter chat. The .AttachEvents() on the .Consume() registered the hooks at the global/bus level rather than at an individual consumer level.

Fix for .AttachEvents() for an individual consumer

---

docs/intro.md
src/Host.Transport.Properties.xml
src/SlimMessageBus.Host.Hybrid/HybridMessageBus.cs
src/SlimMessageBus.Host.Redis/HandlerBuilderExtensions.cs
src/SlimMessageBus.Host/Config/Fluent/AbstractTopicConsumerBuilder.cs
src/SlimMessageBus.Host/Config/Fluent/HandlerBuilder.cs
src/SlimMessageBus.Host/Config/Fluent/MessageBusBuilder.cs
src/SlimMessageBus.Host/Config/Fluent/TopicHandlerBuilder.cs
src/SlimMessageBus.Host/MessageBusBase.cs
src/SlimMessageBus/RequestResponse/IRequestHandler.cs
src/SlimMessageBus/RequestResponse/IRequestResponseBus.cs
src/SlimMessageBus/SlimMessageBus.csproj
src/Tests/SlimMessageBus.Host.Kafka.Test/Config/KafkaProducerBuilderExtensionsTest.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/Config/KafkaProducerSettingsExtensionsTest.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/KafkaMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Redis.Test/RedisMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Test/Config/ConsumerBuilderTest.cs
src/Tests/SlimMessageBus.Host.Test/Config/HandlerBuilderTest.cs

Makes the use of `IRequestMessage<TResponse>` optional. Closes #50.

IRequestHandler<T> optional

---

src/Tests/SlimMessageBus.Host.Integration.Test/HybridTests.cs

Signed-off-by: ahmad <achehre@yahoo.com>
Change Hybrid Test Category
Mark Hybrid tests as integration in the test category. Because it needs the Azure secret key to run.

mark Hybrid tests as integration in test category

---

docs/intro.md
src/Host.Interceptor.Properties.xml
src/Host.Transport.Properties.xml
src/SlimMessageBus.Host/Config/ConsumerSettings.cs
src/SlimMessageBus.Host/Config/Fluent/ConsumerBuilder.cs
src/SlimMessageBus.Host/Config/Fluent/HandlerBuilder.cs
src/SlimMessageBus.Host/Config/Fluent/MessageBusBuilder.cs
src/SlimMessageBus.Host/DependencyResolver/ServiceCollectionExtensions.cs
src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/OutboxTests.cs
src/Tests/SlimMessageBus.Host.Test/Config/ConsumerBuilderTest.cs
src/Tests/SlimMessageBus.Host.Test/Config/HandlerBuilderTest.cs
src/Tests/SlimMessageBus.Host.Test/Config/MessageBusBuilderTests.cs

We can assume the consumer type to `IConsumer<TMessage>` and hence avoid `.WithConsumer<SomeConsumer>()`  most of the time.
Before:
```cs
services.AddSlimMessageBus((mbb, svp) =>
{
mbb.Consume<CustomerCreatedEvent>(x => x
.Topic(topic)
.WithConsumer<CustomerCreatedEventConsumer>() // <------- this
.SubscriptionName("sub");
});
}, addConsumersFromAssembly: new[] { Assembly.GetExecutingAssembly() });
```
After:
```cs
services.AddSlimMessageBus((mbb, svp) =>
{
mbb.Consume<CustomerCreatedEvent>(x => x
.Topic(topic)
.SubscriptionName("sub");
});
}, addConsumersFromAssembly: new[] { Assembly.GetExecutingAssembly() });
```
With this change, the `addConsumersFromAssembly` will register both `CustomerCreatedEventConsumer` and `IConsumer<CustomerCreatedEvent>` in the MSDI.

Default consumer type to the generic interface

---

docs/provider_kafka.md
src/SlimMessageBus.Host.Kafka/Configs/BuilderExtensions.cs
src/SlimMessageBus.Host.Kafka/Configs/KafkaMessageBusBuilderExtensions.cs
src/SlimMessageBus.Host.Kafka/Configs/KafkaMessageBusSettings.cs
src/SlimMessageBus.Host.Kafka/Configs/KafkaProducerBuilderExtensions.cs
src/SlimMessageBus.Host.Kafka/Configs/KafkaProducerSettingsExtensions.cs
src/SlimMessageBus.Host.Kafka/Configs/SettingsExtensions.cs
src/SlimMessageBus.Host.Kafka/Consumer/IKafkaCommitController.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaExtensions.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaGroupConsumer.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaPartitionConsumer.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaPartitionConsumerForConsumers.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaPartitionConsumerForResponses.cs
src/SlimMessageBus.Host.Kafka/DefaultKafkaHeaderSerializer.cs
src/SlimMessageBus.Host.Kafka/GlobalUsings.cs
src/SlimMessageBus.Host.Kafka/KafkaMessageBus.cs
src/SlimMessageBus.Host/RequestResponse/MessageHeaderExtensions.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/DefaultKafkaHeaderSerializerTest.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/GlobalUsings.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/KafkaMessageBusTest.cs

It's better to have a simple serializer for Kafka header values that are set up by default regardless of the chosen message bus serializer.  The proposed serializer converts all the supplied values to string, and the UTF8 encoding is used by default to produce byte[] which the underlying Kafka client requires.
See #155

[Host.Kafka] Kafka default message serializer

---

src/SlimMessageBus.Host.AsyncApi/MessageBusBuilderExtensions.cs
src/SlimMessageBus.Host.AsyncApi/MessageBusDocumentGenerator.cs

On the AsyncApi plugin:
- exclude bus named `Memory` by default
- ability to provide additional filter method to `AddAsyncApiDocumentGenerator()`

[Host.AsyncApi] Exclude Memory named bus by default

---

src/SlimMessageBus.Host.AzureServiceBus/ServiceBusTopologyService.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusTopologySettings.cs

This PR adds option `CanConsumerReplaceSubscriptionFilters` which is set to `false` by default. 
If it's `true`, then whenever any rules are already defined for ASB subscription, then SMB will replace them with newly defined ones.
Context: I observed an issue, if a subscription was defined without the rules, and after some time I decided to add some, then subscription had two rules:
- `$Default`
- and newly added rule
Expected behaviour is to remove the default one, once new rules are declared.
How to use this behaviour: set `ServiceBusTopologySettings`'s `CanConsumerReplaceSubscriptionFilters` flag to true.
Once you do it, if you defined any set of rules, they will override already exisiting ones.
NOTE: It compares already existing rules by name, so let say: if there is a rule with name …

[Host.AzureServiceBus] Add option for replacing already defined rules in ASB subscription

---

docs/intro.md
src/Host.Transport.Properties.xml
src/SlimMessageBus.Host.Configuration/Discovery/ReflectionDiscoveryScanner.cs
src/SlimMessageBus.Host.Memory/MemoryMessageBusBuilder.cs
src/SlimMessageBus.Host/DependencyResolver/ServiceCollectionExtensions.cs
src/Tests/SlimMessageBus.Host.Memory.Test/MemoryMessageBusBuilderTests.cs
src/Tests/SlimMessageBus.Host.Memory.Test/MemoryMessageBusTests.cs
src/Tests/SlimMessageBus.Host.Test/DependencyResolver/ServiceCollectionExtensionsTest.cs

We can now provide the lifetime for the discovered consumers and interceptors.
Before found types were registered as transient only.

[Host] Ability to provide lifetime for .AddServicesFromAssembly() for consumers and interceptors

---

src/Host.Transport.Properties.xml
src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj

The 2.1.5 version experiences the following runtime error:
```
System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyCollection`1<SlimMessageBus.Host.DiscoveryProspectType> SlimMessageBus.Host.ReflectionDiscoveryScanner.GetInterceptorTypes(System.Func`2<System.Type,Boolean>)'.
at SlimMessageBus.Host.ServiceCollectionExtensions.AddServicesFromAssembly(MessageBusBuilder mbb, Assembly assembly, Func`2 filter, ServiceLifetime consumerLifetime, ServiceLifetime interceptorLifetime)
at SlimMessageBus.Host.ServiceCollectionExtensions.AddServicesFromAssemblyContaining[T](MessageBusBuilder mbb, Func`2 filter, ServiceLifetime consumerLifetime, ServiceLifetime interceptorLifetime)
```
The fix is to upgrade the SlimMessageBus.Host.Configuration version.

Fix runtime dependency issue

---

src/SlimMessageBus.Host.Memory/MemoryMessageBus.cs

[Host.Memory] Preserve user's exception's stack details
This is a bug-fix for Host.Memory package.
We have encountered with weird behavior when handling exceptions thrown on consumer side. Essentially exceptions are captured and re-thrown later on and loosing all stack details. In the end it is extremely difficult to trace back the problem if some more generic exception was thrown (e.g. ArgumentNullException from some .net libraries). This PR fixes that problem.
Details about throwing exceptions:
`throw exception;` re-throws exception disregarding existing stack details
`throw;` re-throws exception and keeps existing stack details, however works only in catch block
In this case to preserve exception's details we need to re-throw exception using `ExceptionDispatchInfo` class provided by …

[Host.Memory] Preserve user's exception's stack details

---

src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host/Hybrid/HybridMessageBus.cs
src/SlimMessageBus.Host/Hybrid/HybridMessageBusSettings.cs
src/SlimMessageBus.Host/MessageBusBase.cs
src/Tests/SlimMessageBus.Host.Test.Common/MoqMatchers.cs
src/Tests/SlimMessageBus.Host.Test.Common/XunitLoggerFactory.cs
src/Tests/SlimMessageBus.Host.Test/Hybrid/HybridMessageBusTest.cs

* Hybrid bus now has an additional setting `HybridMessageBusSettings.UndeclaredMessageTypeMode` that allows to set what should happen when a message type is being published that was not declared.
* The default has changed from raising an exception to generation of log (one time)
* Closes #199 
```cs
public class HybridMessageBusSettings
{
/// <summary>
/// When a message type is being produced that has no matching child bus that can produce such a message, defines the mode of execution.
/// </summary>
/// <remarks>The default is <see cref="UndeclaredMessageTypeMode.RaiseOneTimeLog"/>.</remarks>
public UndeclaredMessageTypeMode UndeclaredMessageTypeMode { get; set; } = UndeclaredMessageTypeMode.RaiseOneTimeLog;
}
public enum UndeclaredMessageTypeMode
{
/// <summary>
/// Nothing happens …
```

 [Host.Hybrid] SlimMessageBus.Host.ConfigurationMessageBusException: Could not find any bus that produces the message type

---

docs/provider_azure_servicebus.md
src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.AzureServiceBus/Config/AsbAbstractConsumerSettingsExtensions.cs
src/SlimMessageBus.Host.AzureServiceBus/Config/AsbHasProviderExtensionsExtensions.cs
src/SlimMessageBus.Host.AzureServiceBus/Config/AsbProducerBuilderExtensions.cs
src/SlimMessageBus.Host.AzureServiceBus/Config/Delegates.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBusSettings.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBusSettingsValidationService.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusTopologyService.cs
src/SlimMessageBus.Host.AzureServiceBus/SlimMessageBus.Host.AzureServiceBus.csproj
src/SlimMessageBus.Host.Configuration/Builders/MessageBusBuilder.cs
src/SlimMessageBus.Host.Configuration/Settings/MessageBusSettings.cs
src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj
src/SlimMessageBus.Host.Redis/Consumers/RedisTopicConsumer.cs
src/SlimMessageBus.Host.Redis/RedisMessageBus.cs
src/SlimMessageBus.Host.Redis/RedisUtils.cs
src/SlimMessageBus.Host/Services/MessageHeaderService.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusIt.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusSettingsTests.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusTests.cs
src/Tests/SlimMessageBus.Host.Memory.Test/MemoryMessageBusIt.cs
src/Tests/SlimMessageBus.Host.RabbitMQ.Test/IntegrationTests/RabbitMqMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Redis.Test/RedisMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Test/Collections/SafeDictionaryWrapperTest.cs
src/Tests/SlimMessageBus.Host.Test/Helpers/ReflectionUtilsTests.cs
src/Tests/SlimMessageBus.Host.Test/MessageBusBaseTests.cs
src/Tests/SlimMessageBus.Host.Test/Services/MessageHeaderServiceTests.cs

[Host.AzureServiceBus] Ability to specify SubscriptionName and message modifier defaults

---

docs/provider_rabbitmq.md
src/SlimMessageBus.Host.RabbitMQ/Config/RabbitMqMessageBusSettingsExtensions.cs
src/Tests/SlimMessageBus.Host.RabbitMQ.Test/IntegrationTests/RabbitMqMessageBusIt.cs

- Update RabbitMQ docs to clarify #205
- Fix typo around `.UseTopologyInitializer()` - it was `.UseTopologyInitalizer()`

[Host.RabbitMQ] Document how to achieve concurrent message processing #205

---

src/Common.NuGet.Properties.xml
src/Common.Properties.xml
src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.AzureEventHub/Consumer/EhPartitionConsumer.cs
src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj
src/SlimMessageBus.Host.Interceptor/SlimMessageBus.Host.Interceptor.csproj
src/SlimMessageBus.Host.Kafka/Consumer/IKafkaPartitionConsumer.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaExtensions.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaGroupConsumer.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaPartitionConsumer.cs
src/SlimMessageBus.Host.Kafka/KafkaMessageBus.cs
src/SlimMessageBus.Host.Mqtt/MqttMessageBus.cs
src/SlimMessageBus.Host.Outbox.Sql/SqlOutboxRepository.cs
src/SlimMessageBus.Host.RabbitMQ/RabbitMqTopologyService.cs
src/SlimMessageBus.Host.Serialization/SlimMessageBus.Host.Serialization.csproj
src/SlimMessageBus.Host/Consumer/Checkpointing/CheckpointTrigger.cs
src/SlimMessageBus.Host/Consumer/Checkpointing/CheckpointTriggerFactory.cs
src/SlimMessageBus.Host/Consumer/Checkpointing/CheckpointValue.cs
src/SlimMessageBus.Host/Helpers/CompatMethods.cs
src/SlimMessageBus.Host/Helpers/CompatRecord.cs
src/SlimMessageBus.Host/MessageWithHeaders.cs
src/SlimMessageBus.Host/MessageWithHeadersSerializer.cs
src/SlimMessageBus/SlimMessageBus.csproj
src/Tests/SlimMessageBus.Host.Test/Consumer/CheckpointTriggerFactoryTests.cs
src/Tests/SlimMessageBus.Host.Test/Consumer/CheckpointTriggerTest.cs

[Host.Core] Introduce multi-targeting for net8, net6 and netstandard2.0

---

.github/workflows/build.yml

* Allow to pass secrets for cloned repo PRs to run Sonar and Integration Tests
* The maintainer will need to click approve for every build PR for security reasons

Allow to pass secrets for cloned repo PRs to run Sonar and Integration Tests

---

docs/intro.md
src/SlimMessageBus.Host.Configuration/Builders/AbstractConsumerBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/ConsumerBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/HandlerBuilder.cs
src/SlimMessageBus.Host.Configuration/Settings/ConsumerSettings.cs
src/SlimMessageBus.Host.Configuration/Settings/IMessageTypeConsumerInvokerSettings.cs
src/SlimMessageBus.Host.Configuration/Settings/MessageTypeConsumerInvokerSettings.cs
src/SlimMessageBus.Host/Consumer/Context/ConsumerContext.cs
src/SlimMessageBus.Host/Consumer/MessageProcessors/MessageHandler.cs
src/SlimMessageBus.Host/DependencyResolver/ConsumerMethodPostProcessor.cs
src/SlimMessageBus.Host/Helpers/ReflectionUtils.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Benchmark/ConsumerCallBenchmark.cs
src/Tests/SlimMessageBus.Host.Configuration.Test/ConsumerBuilderTest.cs
src/Tests/SlimMessageBus.Host.Configuration.Test/HandlerBuilderTest.cs
src/Tests/SlimMessageBus.Host.Test/Consumer/MessageHandlerTest.cs
src/Tests/SlimMessageBus.Host.Test/Helpers/ReflectionUtilsTests.cs
src/Tests/SlimMessageBus.Host.Test/SampleMessages.cs

Added support for optionally including IConsumerContext and/or the CancellationToken in the consumer method invocation when supplying a type and method name. 
As the `CancellationToken` is tied to the life of the message lock, it should be readily available in the method to prematurely terminate processing when the lock is lost.
Supplying the `IConsumerContext` as an argument, as opposed to constructor or setting injection, allows for a single consumer instance where appropriate.
```cs
public class SomeConsumer
{
public async Task MyHandleMethod(SomeMessage msg, IConsumerContext consumerContext, CancellationToken cancellationToken)
{
// handle the msg
}
}
```
Please note that the order of the parameters is not important.
---
IConsumer and IRequestHandler have not been modified so as to …

[Host] Optionally include IConsumerContext and/or CancellationToken in consumer method invocation

---

docs/serialization.md
src/Samples/Sample.Serialization.ConsoleApp/Program.cs
src/SlimMessageBus.Host.Configuration/Builders/ISerializationBuilder.cs
src/SlimMessageBus.Host.Configuration/Builders/MessageBusBuilder.cs
src/SlimMessageBus.Host.Serialization.Avro/SerializationBuilderExtensions.cs
src/SlimMessageBus.Host.Serialization.GoogleProtobuf/SerializationBuilderExtensions.cs
src/SlimMessageBus.Host.Serialization.Hybrid/HybridMessageSerializer.cs
src/SlimMessageBus.Host.Serialization.Hybrid/SerializationBuilderExtensions.cs
src/SlimMessageBus.Host.Serialization.Hybrid/SlimMessageBus.Host.Serialization.Hybrid.csproj
src/SlimMessageBus.Host.Serialization.Json/SerializationBuilderExtensions.cs
src/SlimMessageBus.Host.Serialization.SystemTextJson/SerializationBuilderExtensions.cs
src/SlimMessageBus.sln
src/Tests/SlimMessageBus.Host.Serialization.Avro.Test/SerializationBuilderExtensionsTest.cs
src/Tests/SlimMessageBus.Host.Serialization.Hybrid.Test/Helpers/SampleMessages.cs
src/Tests/SlimMessageBus.Host.Serialization.Hybrid.Test/HybridMessageSerializerTests.cs
src/Tests/SlimMessageBus.Host.Serialization.Hybrid.Test/SerializationBuilderExtensionsTests.cs
src/Tests/SlimMessageBus.Host.Serialization.Hybrid.Test/SlimMessageBus.Host.Serialization.Hybrid.Test.csproj
src/Tests/SlimMessageBus.Host.Serialization.Hybrid.Test/Usings.cs
src/Tests/SlimMessageBus.Host.Serialization.SystemTextJson.Test/JsonMessageSerializerTests.cs

#238 PR to allow for serializers to be added and then resolved by the hybrid message serializer. 
By resolving the specialized serializers from the DI container, registration of those serializers can be performed via their included builders. This will then allow for the expected dependency resolution path to be followed for each of the specialized serializers ie. JsonMessageSerializer can use a supplied JsonSerializerOptions instance or resolve one from the DI container directly
***Caveat:***
The HybridMessageSerializer must be registered last so that it is able to remove previous IMessageSerializer registrations in order to make itself the designated serializer.
```c#
services
.AddSlimMessageBus(mbb =>
{
mbb
// add required serializers to the DI container first
.AddAvroSerializer() …
```

[Host.HybridMessageSerialzier] Resolve HybridMessageSerializer dependencies from IServiceProvider

---

docs/provider_azure_servicebus.md
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusTopologyService.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusTopologySettings.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusTopologyServiceTests.cs
src/Tests/SlimMessageBus.Host.Test/SlimMessageBus.Host.Test.csproj
src/Tests/SlimMessageBus.Host.Test/xunit.runner.json

Resolution to exception thrown when attempting to provision topology with Azure Service Bus when multiple consumers share a single subscription.
1. `CreateSubscriptionOptions` across all consumers must be equal
2. Rules are grouped by name. Any grouped rules that are equal are treated as a single rule. Any variation on filters sharing the same name will result in aborting the topology provision.
3. @zarusz - I have added an additional `Updated` status to the `TopologyCreationStatus` enum to reflect success on updating a rule. Is this something that you favour, or should I stick with `Created`?  Do you want `Updated` added but with a value equal to `Created`?
4. An additional `ServiceBusTopologySettings` setting has been added - `CanConsumerValidateSubscriptionFilters`. The setting works …

#244: Topology provision for shared ASB subscription

---

src/SlimMessageBus.Host/Consumer/MessageProcessors/ConcurrencyIncreasingMessageProcessorDecorator.cs
src/SlimMessageBus.Host/Consumer/MessageProcessors/IMessageProcessor.cs
src/SlimMessageBus.Host/Consumer/MessageProcessors/MessageProcessor.cs
src/SlimMessageBus.Host/Consumer/MessageProcessors/ResponseMessageProcessor.cs
src/Tests/SlimMessageBus.Host.Memory.Test/Consumers/ConcurrentMessageProcessorQueueTests.cs
src/Tests/SlimMessageBus.Host.Memory.Test/Consumers/MessageProcessorQueueTests.cs
src/Tests/SlimMessageBus.Host.Test/Consumer/ConcurrencyIncreasingMessageProcessorDecoratorTest.cs
src/Tests/SlimMessageBus.Host.Test/Consumer/ConsumerInstanceMessageProcessorTest.cs

Fixes #256 by disposing a message (if required) once `MessageProcessor<TTransportMessage>.ProcessMessage` has completed the pipeline.
**Please note** that in order for `ProcessMessage` to retain ownership of the `message` object, it can no longer return the `message` object as part of `ProcessMessageResult`. The `Message` property in `ProcessMessageResult` has therefore been removed.

[Host] Dispose message if required

---

README.md
infrastructure.sh
src/Infrastructure/README.md
src/Infrastructure/docker-compose.yml
src/Infrastructure/mosquitto.conf
src/Samples/Sample.AsyncApi.Service/appsettings.json
src/Samples/Sample.Hybrid.ConsoleApp/appsettings.json
src/Samples/Sample.OutboxWebApi/Program.cs
src/Samples/Sample.OutboxWebApi/appsettings.json
src/Samples/Sample.Serialization.ConsoleApp/Program.cs
src/Samples/Sample.Serialization.ConsoleApp/appsettings.json
src/Samples/Sample.Simple.ConsoleApp/Program.cs
src/Samples/Sample.Simple.ConsoleApp/appsettings.json
src/SlimMessageBus.sln
src/Tests/SlimMessageBus.Host.AzureEventHub.Test/appsettings.json
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusIt.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/appsettings.json
src/Tests/SlimMessageBus.Host.Integration.Test/appsettings.json
src/Tests/SlimMessageBus.Host.Kafka.Test/KafkaMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/appsettings.json
src/Tests/SlimMessageBus.Host.Mqtt.Test/MqttMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Mqtt.Test/appsettings.json
src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/OutboxTests.cs
src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/appsettings.json
src/Tests/SlimMessageBus.Host.RabbitMQ.Test/appsettings.json
src/Tests/SlimMessageBus.Host.Redis.Test/appsettings.json
src/Tools/SecretStore/FileSecretStore.cs
src/Tools/SecretStore/SecretService.cs
src/secrets.txt.sample

Testing if you aren't @zarusz can be a little painful with the test configurations tailored for private resources ;)
Please consider this PR. It allows for a full test coverage running everything locally except for Azure Service Bus and Azure Event Hub which don't have containers available.
To ease some of the integration, Kafka and Mqtt are both hosted without certs. It does require some minor changes to some of the bootstrapping for the integration tests, but won't have any impact (beyond configuration) for the build pipeline.
I understand that build pipeline will be broken with the change, but that should be easily resolved by updating the devops version of secrets.txt with the sample provided.
1. Copy `src/secrets.txt.sample` to `src/secrets.txt`
2. Add connection strings for personal …

[Integration testing] Containers for local development

---

infrastructure.ps1
src/Host.Plugin.Properties.xml
src/Infrastructure/README.md
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/SlimMessageBus.Host.Interceptor/Bus/MessageBusLifecycleEventType.cs
src/SlimMessageBus.Host.Outbox/Interceptors/OutboxSendingTask.cs
src/SlimMessageBus.Host/MessageBusBase.cs
src/SlimMessageBus.sln
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusIt.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusTests.cs
src/Tests/SlimMessageBus.Host.Integration.Test/HybridTests.cs
src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/BusType.cs
src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/DatabaseFacadeExtenstions.cs
src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/OutboxBenchmarkTests.cs
src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/OutboxTests.cs
src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/TransactionType.cs
src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/Usings.cs
src/Tests/SlimMessageBus.Host.Test.Common/IntegrationTest/BaseIntegrationTest.cs
src/Tests/SlimMessageBus.Host.Test.Common/MoqExtensions.cs
src/Tests/SlimMessageBus.Host.Test/Consumer/ConsumerInstanceMessageProcessorTest.cs
src/Tests/SlimMessageBus.Host.Test/GlobalUsings.cs
src/Tests/SlimMessageBus.Host.Test/Hybrid/HybridMessageBusTest.cs
src/Tests/SlimMessageBus.Host.Test/MessageBusBaseTests.cs
src/Tests/SlimMessageBus.Host.Test/MessageBusTested.cs
src/Tests/SlimMessageBus.Host.Test/SampleMessages.cs
src/secrets.txt.sample

- Ensure SQL tables are provisioned before the first publish (and without having to start consumers).
- Send Created bus lifecycle event to be able to hook into Master bus creation
- Add baseline performance test for Outbox.
The test (`OutboxBenchmarkTests`) would be run locally against the same machine (GitHub Actions agent). It collects the times it took to produce and then consumes N messages. We can use the times to compare if the new enhancements are better.  In the future more types of use cases could be added to baseline the Outbox from different angles.
For example, a run from my local machine to the Azure Service Bus + Azure SQL instance, for 1000 messages:
With Outbox:
```
[12:59:34 INF] SlimMessageBus.Host.Outbox.DbContext.Test.OutboxBenchmarkTests Message Publish took: …
```

[Host.Outbox] Ensure SQL tables are provisioned and baseline test

---

src/SlimMessageBus.Host.Outbox/Interceptors/OutboxSendingTask.cs

`OutboxSendingTask.MigrateSchema` resolves `IOutboxMigrationService` within a scope to satisfy `ISqlOutboxRepository` registration.
```
System.InvalidOperationException: 'Cannot resolve 'SlimMessageBus.Host.Outbox.IOutboxMigrationService' from root provider because it requires scoped service 'SlimMessageBus.Host.Outbox.Sql.ISqlOutboxRepository'.'
```

#273 Wrap IOutboxMigrationService resolution in a scope

---

.github/workflows/build.yml
src/SlimMessageBus.sln
src/Tests/SecretStore.Test/EnvironmentVariableSecretStoreTests.cs
src/Tests/SecretStore.Test/FileSecretStoreTests.cs
src/Tests/SecretStore.Test/SecretStore.Test.csproj
src/Tests/SecretStore.Test/Usings.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/KafkaMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Mqtt.Test/MqttMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/OutboxBenchmarkTests.cs
src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/OutboxTests.cs
src/Tests/SlimMessageBus.Host.RabbitMQ.Test/IntegrationTests/RabbitMqMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Redis.Test/RedisMessageBusIt.cs
src/Tools/SecretStore/EnvironmentVariableSecretStore.cs
src/Tools/SecretStore/FileSecretStore.cs

* Add docker step to create test containers
* Repoint most of the transports to the test containers

[Integration tests] Add docker step for test containers

---

src/SlimMessageBus.Host.Outbox/Services/OutboxLockRenewalTimer.cs
src/Tests/SlimMessageBus.Host.Outbox.Test/OutboxLockRenewalTimerTests.cs

`OutboxLockRenewalTimer` throws an exception on `CancellationToken` expiration instead of handling the cancellation gracefully/returning.

[Host.Outbox] Return gracefully from OutboxLockRenewalTimer on token cancellation

---

.github/workflows/build.yml

The zulu JDK distro cannot be pulled at the moment. Switching to another distribution.
Similar issue: https://github.com/actions/setup-java/issues/335

Switch to adopt JDK distro for SonarCloud

---

.github/workflows/build.yml
docs/README.md
docs/provider_nats.md
docs/provider_nats.t.md
src/Infrastructure/docker-compose.yml
src/Samples/Infrastructure/Nats-SingleNode/docker-compose.yml
src/Samples/Sample.Nats.WebApi/PingConsumer.cs
src/Samples/Sample.Nats.WebApi/PingMessage.cs
src/Samples/Sample.Nats.WebApi/Program.cs
src/Samples/Sample.Nats.WebApi/Properties/launchSettings.json
src/Samples/Sample.Nats.WebApi/Sample.Nats.WebApi.csproj
src/Samples/Sample.Nats.WebApi/appsettings.Development.json
src/Samples/Sample.Nats.WebApi/appsettings.json
src/SlimMessageBus.Host.Nats/Config/MessageBusBuilderExtensions.cs
src/SlimMessageBus.Host.Nats/GlobalUsings.cs
src/SlimMessageBus.Host.Nats/NatsHeadersExtensions.cs
src/SlimMessageBus.Host.Nats/NatsMessageBus.cs
src/SlimMessageBus.Host.Nats/NatsMessageBusSettings.cs
src/SlimMessageBus.Host.Nats/NatsMessageBusSettingsValidationService.cs
src/SlimMessageBus.Host.Nats/NatsSubjectConsumer.cs
src/SlimMessageBus.Host.Nats/SlimMessageBus.Host.Nats.csproj
src/SlimMessageBus.Host/MessageBusBase.cs
src/SlimMessageBus.sln
src/Tests/SlimMessageBus.Host.Nats.Test/GlobalUsings.cs
src/Tests/SlimMessageBus.Host.Nats.Test/NatsMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Nats.Test/SlimMessageBus.Host.Nats.Test.csproj
src/Tests/SlimMessageBus.Host.Nats.Test/Usings.cs
src/Tests/SlimMessageBus.Host.Nats.Test/appsettings.json
src/secrets.txt.sample

Nats.io transport added
Support for Pub/Sub and Request/Response functionalities

[Host.Nats] Transport for Nats.io

---

docs/plugin_outbox.md
src/Host.Plugin.Properties.xml
src/Samples/Sample.OutboxWebApi/Program.cs
src/SlimMessageBus.Host.Memory/MemoryMessageBusBuilder.cs
src/SlimMessageBus.Host.Outbox.Sql/Configuration/BuilderExtensions.cs
src/SlimMessageBus.Host.Outbox.Sql/Configuration/MessageBusBuilderExtensions.cs
src/SlimMessageBus.Host.Outbox.Sql/GlobalUsings.cs
src/SlimMessageBus.Host.Outbox.Sql/Interceptors/SqlTransactionConsumerInterceptor.cs
src/SlimMessageBus.Host.Outbox/Configuration/BuilderExtensions.cs
src/SlimMessageBus.Host.Outbox/Configuration/MessageBusBuilderExtensions.cs
src/SlimMessageBus.Host.Outbox/Configuration/SettingsExtensions.cs
src/SlimMessageBus.Host.Outbox/Interceptors/TransactionScopeConsumerInterceptor.cs

What:
Adding an option to determine message types filter in the following outbox declarations:
```cs
mbb.UseOutbox(messageTypeFilter: t => t.Name.EndsWith("Command"));
mbb.UseSqlTransaction(messageTypeFilter: t => t.Name.EndsWith("Command"));
mbb.UseTransactionScope(messageTypeFilter: t => t.Name.EndsWith("Command"));
```
The filtering happens at configuration time.
Why:
We can have an In-Memory bus for CQRS where only command messages require to be wrapped in a transaction and query messages do not. Without it we would have to declare two memory child buses - for commands and queries.
Optimization:
Moreover, the `UseSqlTransaction()` will be registered for the enabled message types (consumers, or bus) only. 
Before the interceptor was registered DI wide, and interceptor was checking …

[Host.Outbox] Ability to filter UseSqlTransaction and UseOutbox by message type

---

.github/workflows/build.yml
docs/provider_kafka.md
docs/provider_kafka.t.md
src/Host.Plugin.Properties.xml
src/Infrastructure/docker-compose.yml
src/SlimMessageBus.Host.Kafka/Consumer/IKafkaPartitionConsumer.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaGroupConsumer.cs
src/SlimMessageBus.Host.Kafka/Consumer/KafkaPartitionConsumer.cs
src/SlimMessageBus.Host.Kafka/KafkaMessageBus.cs
src/SlimMessageBus.Host.Kafka/SlimMessageBus.Host.Kafka.csproj
src/Tests/SlimMessageBus.Host.Kafka.Test/Consumer/KafkaGroupConsumerTests.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/Consumer/KafkaPartitionConsumerForConsumersTest.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/Consumer/KafkaPartitionConsumerForResponsesTest.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/GlobalUsings.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/KafkaMessageBusIt.cs
src/Tests/SlimMessageBus.Host.Kafka.Test/appsettings.json
src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/OutboxTests.cs

There was an issue raised in [#131](https://github.com/zarusz/SlimMessageBus/issues/131#issuecomment-2344638738). Doing further investigation I have found:
- With `EnablePartitionEof` set to `true`, when the partition ended, SMB was committing too advanced a partition index.
- The SMB-driven manual commit with the `CheckpointAfter(TimeSpan)` might not happen after the desired time when there are no protocol events that happen (partition assignment or partition EOF).
Moreover, the Confluent.Kafka library has being upgraded from 2.3.0 to 2.5.2.

[Host.Kafka] Fix and improve commit logic

---

docs/provider_azure_servicebus.md
src/SlimMessageBus.Host.AzureServiceBus/Config/AsbAbstractConsumerSettingsExtensions.cs
src/SlimMessageBus.Host.AzureServiceBus/Config/AsbConsumerBuilderExtensions.cs
src/SlimMessageBus.Host.AzureServiceBus/Config/SubscriptionCorrelationRule.cs
src/SlimMessageBus.Host.AzureServiceBus/Config/SubscriptionRule.cs
src/SlimMessageBus.Host.AzureServiceBus/Config/SubscriptionSqlFilter.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusTopologyService.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusTopologyServiceTests.cs

[Correlation filters](https://learn.microsoft.com/en-us/azure/service-bus-messaging/topic-filters#correlation-filters) are more efficient then SQL filters and are the preferred way to implement filtering when the features of SQL rule filters are not required.
```c#
mbb.Consume<SomeMessage>(x => x
.Topic("some-topic")
.WithConsumer<SomeMessageConsumer>()
.SubscriptionName("some-service")
.SubscriptionCorrelationFilter(correlationId: "some-correlation-id", contentType: "application/json")
.CreateTopicOptions((options) =>
{
options.RequiresDuplicateDetection = false;
})
);
```

[Host.AzureServiceBus] #349 Correlation filters

---

docs/intro.md
docs/intro.t.md

I just saw how the footnote was rendered in the error handling documentation. It wasn't pretty. Here's a small change to keep the details together.

[Host] Error handling documentation improvement

---

docs/intro.md
docs/provider_azure_servicebus.md
src/SlimMessageBus.Host.AzureServiceBus/Consumer/AsbBaseConsumer.cs
src/SlimMessageBus.Host.AzureServiceBus/Consumer/IServiceBusConsumerErrorHandler.cs
src/SlimMessageBus/IConsumerWithContext.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusIt.cs

#358 Added support for suppliying modified user properties with using an ASB transport when using a custom `ServiceBusConsumerErrorHandler<T>` implemntation and `Failure()`.
```cs
public sealed class SampleConsumerErrorHandler<T> : ServiceBusConsumerErrorHandler<T>
{
public override Task<ProcessResult> OnHandleError(T message, IConsumerContext consumerContext, Exception exception, int attempts)
{
var properties = new Dictionary<string, object>
{
{ "Key", "value" },
{ "Attempts", attempts },
{ "SMB.Exception", exception.ToString().Substring(0, 1000) }
};
return Task.FromResult(Failure(properties));
}
}
```
---
An option to supply a dead-letter reason/description when sending a message to the DLQ has also been included. If neither a reason nor description are supplied, it will fall back to …

[Host.AzureServiceBus] Modify user properties on failure / Supply reason and description on dead-letter

---

src/SlimMessageBus.Host.AzureServiceBus/ServiceBusTopologyService.cs

#367 Refactored `ServiceBusTopologyService` to execute subscription creation in parallel per topic. 
---
Anecdotal perforamance improvment when creating n subscriptions (each with a correlation rule and 5 sql filter rules). Approx. 66ms [latency](https://www.azurespeed.com/Azure/Latency) to the Azure data centre.
| Subscriptions | Before |After|
|---|---|---|
|10 | 00:00:18.6069600 | 00:00:05.2469819 |
|100 | 00:02:42.2289160 |00:00:21.2268600 |

[Host.AzureServiceBus] Create subscriptions in parallel

---

docs/provider_azure_servicebus.md
src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.AzureServiceBus/Consumer/ServiceBusConsumerContextExtensions.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj
src/SlimMessageBus.Host.Serialization/SlimMessageBus.Host.Serialization.csproj
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusIt.cs

[Host.AzureServiceBus] Expose SubscriptionName under IConsumerContext

---

src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj
src/SlimMessageBus.Host.RabbitMQ/Config/ExchangeType.cs
src/SlimMessageBus.Host.RabbitMQ/Config/RabbitMqConsumerBuilderExtensions.cs
src/SlimMessageBus.Host.RabbitMQ/Config/RabbitMqConsumerContextExtensions.cs
src/SlimMessageBus.Host.RabbitMQ/Config/RabbitMqMessageBusSettingsExtensions.cs
src/SlimMessageBus.Host.RabbitMQ/Config/RabbitMqProducerBuilderExtensions.cs
src/SlimMessageBus.Host.RabbitMQ/Config/RabbitMqProperties.cs
src/SlimMessageBus.Host.RabbitMQ/Config/RabbitMqRequestResponseBuilderExtensions.cs
src/SlimMessageBus.Host.RabbitMQ/Consumers/RabbitMqConsumer.cs
src/SlimMessageBus.Host.RabbitMQ/RabbitMqMessageBus.cs
src/Tests/SlimMessageBus.Host.RabbitMQ.Test/Config/RabbitMqConsumerBuilderExtensionsTests.cs
src/Tests/SlimMessageBus.Host.RabbitMQ.Test/Config/RabbitMqMessageBusSettingsExtensionsTests.cs

- Convert `ExchangeType` from enum to a string to allow to pass custom exchange types
- Introduce the `x-delayed-message` static value to account for delayed message Rabbit plugin as per #396

[Host.RabbitMq] Convert ExchangeType from enum to a string

---

docs/provider_memory.md
docs/provider_memory.t.md
src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.Memory/MemoryMessageBusBuilder.cs
src/Tests/SlimMessageBus.Host.Memory.Test/MemoryMessageBusBuilderTests.cs

- Updated the default message type-to-topic name resolution in `mbb.AutoDeclareFrom()` to use the message type's [`FullName`](https://learn.microsoft.com/en-us/dotnet/api/system.type.fullname?view=net-9.0).
- Previously, only the type `Name` was used, which could lead to naming clashes (e.g., as reported in #399).

[Host.Memory] mbb.AutoDeclareFrom() to use message type FullName by default

---

src/SlimMessageBus.Host.Redis/Consumers/RedisListCheckerConsumer.cs
src/SlimMessageBus.Host.Redis/RedisMessageBusSettings.cs
src/Tests/SlimMessageBus.Host.Redis.Test/RedisListCheckerConsumerTest.cs

fixes #419 by catching exceptions
It retries the next queue "automatically" because it's inside the loop.
Draft because I didn't add a test case. Not really sure how to simulate a disconnect and reconnect inside a test.

[Host.Redis] prevent RedisListCheckerConsumer from crashing on disconnect 

---

src/Host.Plugin.Properties.xml
src/SlimMessageBus.Host.AzureEventHub/EventHubMessageBus.cs
src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj
src/Tests/SlimMessageBus.Host.AzureEventHub.Test/EventHubMessageBusIt.cs
src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusIt.cs

Fixes an issue in the Bulk Message Publish API where message chunking could fail at chunk boundaries, causing some messages to be skipped.
The problem occurred because chunking was adaptive - based on the buffer capacity reported by Azure Service Bus (ASB) or Azure Event Hubs (AEH) - and varied with message size. When large batches of messages were published at once via the Bulk Message API, this sometimes resulted in incorrect chunking and message loss at the boundary.
This PR corrects the chunking logic to ensure all messages are properly published without being skipped.
- Azure Service Bus
- Azure Event Hubs

[Host.AzureServiceBus][Host.AzureEventHub] Fix the batch publish chunking iterations

---

docs/provider_rabbitmq.md
src/SlimMessageBus.Host.RabbitMQ/RabbitMqMessageBusSettingsValidationService.cs
src/SlimMessageBus.Host.RabbitMQ/RabbitMqTopologyService.cs
src/Tests/SlimMessageBus.Host.RabbitMQ.Test/IntegrationTests/RabbitMqDefaultExchangeIt.cs
src/Tests/SlimMessageBus.Host.RabbitMQ.Test/RabbitMqMessageBusSettingsValidationServiceTests.cs
src/Tests/SlimMessageBus.Host.RabbitMQ.Test/RabbitMqTopologyServiceTests.cs

Enhances validation for consumer and producer settings to properly support the **default exchange**.
- ✅ Avoids declaring or binding the default exchange (handled internally by RabbitMQ).  
- ✅ Adds clearer error messages for missing or invalid configuration.  
- ✅ Logs when default exchange operations are intentionally skipped.  
ℹ️ This ensures correct behavior when working with the default exchange (`""`), which is a pre-declared direct exchange that automatically binds queues by their name.

[Host.RabbitMQ] Improve Validation and Default Exchange Handling
